#!/usr/bin/expect -f

exp_internal 1

set timeout -1

spawn  suitecloud account:setup

expect "*Create a new authentication ID (authID).*"
send -- "\r\n"

expect "*Browser-based authentication*"
send -- "\[B"
send -- "\r\n"


expect "*Enter an authentication ID (authID):*"
send -- "FekadTest"
send -- "\r\n"


expect "*Enter the account ID:*"
send -- "12345"
send -- "\r\n"

expect "*Enter the Token ID:*"
send -- "1234567890"
send -- "\r\n"

expect "*Enter the Token Secret:*"
send -- "1234567890"
send -- "\r\n"

puts "The output is '$expect_out(buffer)'."
expect eof


