name: 'NetSuite:SDF'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: begin-echo
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash


    - name: Install Node JS
      run: sudo apt install nodejs
      shell: bash
    - id: after-node-install
      run: echo '### Node installed'.
      shell: bash

    - name: Install Node JS
      run: sudo apt install npm
      shell: bash
    - id: after-npm-install
      run: echo '### NPM installed'.
      shell: bash


    - name: SuiteCloud API Install
      run: sudo npm install -g @oracle/suitecloud-cli
      shell: bash
    - id: after-sdf-install
      run: echo '### SDF installed'.
      shell: bash

    - name: Install Expect
      run: sudo apt-get install -y expect tcl-expect
      shell: bash
    - id: after-expect-install
      run: echo '### Express installed'.
      shell: bash


    - id: after-node-suitecloud
      run: echo '###  SDF installed'.
      shell: bash

    - run: expect ${{ github.action_path }}/account-setup.exp
      shell: bash