name: 'NetSuite:SDF'
description: 'Greet someone'
inputs:
  account:  # id of input
    description: 'Your NetSuite Account Id'
    required: true
    default: 'World'
  token:  # id of input
    description: 'Token ID for authentication'
    required: true
    default: 'World'
  secret:  # id of input
    description: 'Token Secret for authentication'
    required: true
    default: 'World'
  title:  # id of input
    description: 'Connection Name'
    required: false
    default: "NS-Auth-$(echo $RANDOM)"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: begin-echo
      run: echo Setting up NS \# ${{ inputs.account}}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash

    - name: SuiteCloud API Install
      run: npm install -g @oracle/suitecloud-cli
      shell: bash
    - id: after-sdf-install
      run: echo '### SDF installed'.
      shell: bash

    # - name: Install Expect
    #   run: sudo apt-get install -y expect tcl-expect
    #   shell: bash
    # - id: after-expect-install
    #   run: echo '### Expect installed'.
    #   shell: bash

    # - run: expect ${{ github.action_path }}/account-setup.exp ${{ inputs.account }} ${{ inputs.token}} ${{ inputs.secret }} ${{ inputs.title }}
    #   shell: bash

    - name: Setup Account
      run: suitecloud account:savetoken -account ${{ inputs.account }} -authid ${{ inputs.title }} -tokenid ${{ inputs.token }} -tokensecret ${{ inputs.secret }}
      shell: bash

    - run: cat deploy.xml
      shell: bash

    - run: ls -trla
      shell: bash

    - run: suitecloud project:deploy
      shell: bash